### PR TITLE
Add Union, float types, allow empty Lists

### PR DESCRIPTION
**Pull request by StephenBrown2**
Hello! I've enjoyed using this tool to convert a bunch of my JSON API schemas to dataclasses, but I've found it a little lacking, so I hope these improvements are welcome.

This PR:
- adds the ability for a `Union` of disparate types in a `List`
- checks if numbers in lists should be `float`s rather than `int`s
- accounts for empty lists, leaving the key with a blank `List` type

Example result (note `demo_tuple` and see that `residents` is present):
Screenshot 2020-04-15 at 13 20 11

### CODE REVIEW

**Comment by russbiggs** [comment]
@StephenBrown2 Glad to hear its helpful.  This contribution is very welcome and seems like a good improvement.  I'll take a look this afternoon.

**Comment by StephenBrown2** [comment]
Sure thing. I did notice also that strings comprised of 4 digits match the datetime regex, even if they aren't actually years, so I might tighten the matching, but didn't want to add that to this PR.

**Comment by russbiggs** [comment]
This looks really good.  The only thing that I noticed is if there is a datetime in the array the Union doesn't pick it up when the ```use datetime.datetime``` is checked.  Can you add the datetime check into the Union construction?

**Comment by StephenBrown2** [comment]
I swapped out the type detection in the list for `findType`, which will allow for the same logic to detect datetimes et al in both places.

The Set logic could potentially be pulled out to handle multiple types in different instances of the object, which I've seen before (e.g. something is a float in multiple objects but only sometimes isn't a whole number), but that's also an idea for later.

**Pull request merged**
